/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DBConnection;
import Model.Ban;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLyBan extends javax.swing.JPanel {

    ThemBan themBan;
    SuaBan suaBan;

    /**
     * Creates new form QuanLyNV
     */
    public QuanLyBan() {
        initComponents();
        loadBan();
    }

    public static void loadBan() {
        String[] title = {"Mã Bàn", "Số Lượng Chỗ", "Vị Trí", "Trạng Thái"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(title, 0);
        DBConnection dBConnection = new DBConnection();
        ArrayList<Ban> banList = dBConnection.getDSBan();
        for (int i = 0; i < banList.size(); i++) {
            Vector vector = new Vector();
            vector.add(banList.get(i).getMaBan());
            vector.add(banList.get(i).getSoLuongCho());
            vector.add(banList.get(i).getViTri());
            vector.add(banList.get(i).getTrangThai());
            defaultTableModel.addRow(vector);
        }        
        tableQuanLyBan.setRowHeight(35);
        tableQuanLyBan.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuanLyBan = new javax.swing.JTable();
        btnSua = new javax.swing.JLabel();
        btnThem = new javax.swing.JLabel();
        btnXoa = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tableQuanLyBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableQuanLyBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableQuanLyBan);

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setPreferredSize(new java.awt.Dimension(81, 32));
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSuaMousePressed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThemMousePressed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setPreferredSize(new java.awt.Dimension(81, 32));
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnXoaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 528, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMousePressed
        // TODO add your handling code here:
        themBan = new ThemBan(null, true);
        themBan.setVisible(true);

    }//GEN-LAST:event_btnThemMousePressed

    private void btnSuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMousePressed
        // TODO add your handling code here:

        try {
            SuaBan.maBan = tableQuanLyBan.getValueAt(tableQuanLyBan.getSelectedRow(), 0).toString();
            SuaBan.soluong = Integer.parseInt(tableQuanLyBan.getValueAt(tableQuanLyBan.getSelectedRow(), 1).toString());
            SuaBan.viTri = tableQuanLyBan.getValueAt(tableQuanLyBan.getSelectedRow(), 2).toString();
            SuaBan.trangThai = tableQuanLyBan.getValueAt(tableQuanLyBan.getSelectedRow(), 3).toString();
            suaBan = new SuaBan(null, true);
            suaBan.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng bạn muốn chỉnh sửa!!!");
        }

    }//GEN-LAST:event_btnSuaMousePressed

    private void btnXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMousePressed
        // TODO add your handling code here:
        String maban = tableQuanLyBan.getValueAt(tableQuanLyBan.getSelectedRow(), 0).toString();
        int soluong = Integer.parseInt(tableQuanLyBan.getValueAt(tableQuanLyBan.getSelectedRow(), 1).toString());
        String vitri = tableQuanLyBan.getValueAt(tableQuanLyBan.getSelectedRow(), 2).toString();
        String trangthai = tableQuanLyBan.getValueAt(tableQuanLyBan.getSelectedRow(), 3).toString();
        Ban b = new Ban(maban,soluong,vitri,trangthai);
        DBConnection dBConnection = new DBConnection();
        int res = JOptionPane.showConfirmDialog(this, "Bạn có muốn tiếp tục?", "Xác nhận ", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            dBConnection.deleteBan(b);
            loadBan();
        }
    }//GEN-LAST:event_btnXoaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnThem;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tableQuanLyBan;
    // End of variables declaration//GEN-END:variables
}
