/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class QuanLy extends javax.swing.JPanel {

    QuanLyNhanVien quanLyNV;
    QuanLyBan quanLyBan;
    QuanLyChucVu quanLyCV;
    QuanLyDanhMuc quanLyDM;
    QuanLyMon quanLyMon;

    /**
     * Creates new form Panel
     */
    public QuanLy() {
        initComponents();
        jPanel2.setLayout(new GridLayout());
        quanLyBan = new QuanLyBan();
        quanLyNV = new QuanLyNhanVien();
        quanLyCV = new QuanLyChucVu();
        quanLyDM = new QuanLyDanhMuc();
        quanLyMon = new QuanLyMon();
        jPanel2.add(quanLyNV);
        quanLyNV.setVisible(true);
    }

    void setColor(JPanel p) {
        p.setBackground(new Color(250,243,243));
    }

    void resetColor(JPanel p) {
        p.setBackground(new Color(250,248,248));
    }

    void add(JPanel p) {
        jPanel2.removeAll();
        jPanel2.add(p);
        p.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelQuanLyNhanVien = new javax.swing.JPanel();
        btnQLNV = new javax.swing.JLabel();
        panelQuanLyChucVu = new javax.swing.JPanel();
        btnQLCV = new javax.swing.JLabel();
        panelQuanLyDanhMuc = new javax.swing.JPanel();
        btnQLDM = new javax.swing.JLabel();
        panelQuanLyBan = new javax.swing.JPanel();
        btnQLB = new javax.swing.JLabel();
        panelQuanLyMon = new javax.swing.JPanel();
        btnQLM = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1400, 824));

        jPanel1.setBackground(new java.awt.Color(250, 248, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelQuanLyNhanVien.setBackground(new java.awt.Color(250, 248, 248));

        btnQLNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/QLNV.png"))); // NOI18N
        btnQLNV.setText("Quản Lý Nhân Viên");
        btnQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLNVMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelQuanLyNhanVienLayout = new javax.swing.GroupLayout(panelQuanLyNhanVien);
        panelQuanLyNhanVien.setLayout(panelQuanLyNhanVienLayout);
        panelQuanLyNhanVienLayout.setHorizontalGroup(
            panelQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelQuanLyNhanVienLayout.setVerticalGroup(
            panelQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLyNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 344, -1));

        panelQuanLyChucVu.setBackground(new java.awt.Color(250, 248, 248));

        btnQLCV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/QLCV.png"))); // NOI18N
        btnQLCV.setText("Quản Lý Chức Vụ");
        btnQLCV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLCVMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelQuanLyChucVuLayout = new javax.swing.GroupLayout(panelQuanLyChucVu);
        panelQuanLyChucVu.setLayout(panelQuanLyChucVuLayout);
        panelQuanLyChucVuLayout.setHorizontalGroup(
            panelQuanLyChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyChucVuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelQuanLyChucVuLayout.setVerticalGroup(
            panelQuanLyChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLyChucVuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQLCV)
                .addContainerGap())
        );

        jPanel1.add(panelQuanLyChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 344, -1));

        panelQuanLyDanhMuc.setBackground(new java.awt.Color(250, 248, 248));

        btnQLDM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLDM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/QLDM.png"))); // NOI18N
        btnQLDM.setText("Quản Lý Danh Mục");
        btnQLDM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLDMMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelQuanLyDanhMucLayout = new javax.swing.GroupLayout(panelQuanLyDanhMuc);
        panelQuanLyDanhMuc.setLayout(panelQuanLyDanhMucLayout);
        panelQuanLyDanhMucLayout.setHorizontalGroup(
            panelQuanLyDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyDanhMucLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelQuanLyDanhMucLayout.setVerticalGroup(
            panelQuanLyDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyDanhMucLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelQuanLyDanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 344, 90));

        panelQuanLyBan.setBackground(new java.awt.Color(250, 248, 248));

        btnQLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/QLB.png"))); // NOI18N
        btnQLB.setText("Quản Lý Bàn");
        btnQLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLBMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelQuanLyBanLayout = new javax.swing.GroupLayout(panelQuanLyBan);
        panelQuanLyBan.setLayout(panelQuanLyBanLayout);
        panelQuanLyBanLayout.setHorizontalGroup(
            panelQuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelQuanLyBanLayout.setVerticalGroup(
            panelQuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLyBanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQLB)
                .addContainerGap())
        );

        jPanel1.add(panelQuanLyBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 344, -1));

        panelQuanLyMon.setBackground(new java.awt.Color(250, 248, 248));

        btnQLM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/QLM.png"))); // NOI18N
        btnQLM.setText("Quản Lý Món");
        btnQLM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLMMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelQuanLyMonLayout = new javax.swing.GroupLayout(panelQuanLyMon);
        panelQuanLyMon.setLayout(panelQuanLyMonLayout);
        panelQuanLyMonLayout.setHorizontalGroup(
            panelQuanLyMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelQuanLyMonLayout.setVerticalGroup(
            panelQuanLyMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelQuanLyMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 344, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLNVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMousePressed
        // TODO add your handling code here:
        quanLyBan.setVisible(false);
        quanLyCV.setVisible(false);
        quanLyDM.setVisible(false);
        quanLyMon.setVisible(false);
        quanLyNV = new QuanLyNhanVien();
        setColor(panelQuanLyNhanVien);
        resetColor(panelQuanLyChucVu);
        resetColor(panelQuanLyDanhMuc);
        resetColor(panelQuanLyBan);
        resetColor(panelQuanLyMon);     
        add(quanLyNV);
    }//GEN-LAST:event_btnQLNVMousePressed

    private void btnQLCVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLCVMousePressed
        // TODO add your handling code here:
        quanLyBan.setVisible(false);
        quanLyNV.setVisible(false);
        quanLyDM.setVisible(false);
        quanLyMon.setVisible(false);
        quanLyCV = new QuanLyChucVu();
        setColor(panelQuanLyChucVu);
        resetColor(panelQuanLyNhanVien);
        resetColor(panelQuanLyDanhMuc);
        resetColor(panelQuanLyBan);
        resetColor(panelQuanLyMon);  
        add(quanLyCV);
    }//GEN-LAST:event_btnQLCVMousePressed

    private void btnQLBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLBMousePressed
        // TODO add your handling code here:
        quanLyNV.setVisible(false);
        quanLyCV.setVisible(false);
        quanLyDM.setVisible(false);
        quanLyMon.setVisible(false);
        quanLyBan = new QuanLyBan();
        setColor(panelQuanLyBan);
        resetColor(panelQuanLyChucVu);
        resetColor(panelQuanLyDanhMuc);
        resetColor(panelQuanLyNhanVien);
        resetColor(panelQuanLyMon);  
        add(quanLyBan);
    }//GEN-LAST:event_btnQLBMousePressed

    private void btnQLMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLMMousePressed
        // TODO add your handling code here:
        quanLyBan.setVisible(false);
        quanLyNV.setVisible(false);
        quanLyCV.setVisible(false);
        quanLyDM.setVisible(false);
        quanLyMon = new QuanLyMon();
        setColor(panelQuanLyMon);
        resetColor(panelQuanLyChucVu);
        resetColor(panelQuanLyDanhMuc);
        resetColor(panelQuanLyBan);
        resetColor(panelQuanLyNhanVien);  
        add(quanLyMon);
    }//GEN-LAST:event_btnQLMMousePressed

    private void btnQLDMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDMMousePressed
        // TODO add your handling code here:
        quanLyBan.setVisible(false);
        quanLyNV.setVisible(false);
        quanLyCV.setVisible(false);
        quanLyMon.setVisible(false);
        quanLyDM = new QuanLyDanhMuc();
        setColor(panelQuanLyDanhMuc);
        resetColor(panelQuanLyChucVu);
        resetColor(panelQuanLyMon);
        resetColor(panelQuanLyBan);
        resetColor(panelQuanLyNhanVien);  
        add(quanLyDM);
    }//GEN-LAST:event_btnQLDMMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnQLB;
    private javax.swing.JLabel btnQLCV;
    private javax.swing.JLabel btnQLDM;
    private javax.swing.JLabel btnQLM;
    private javax.swing.JLabel btnQLNV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelQuanLyBan;
    private javax.swing.JPanel panelQuanLyChucVu;
    private javax.swing.JPanel panelQuanLyDanhMuc;
    private javax.swing.JPanel panelQuanLyMon;
    private javax.swing.JPanel panelQuanLyNhanVien;
    // End of variables declaration//GEN-END:variables
}
