/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DBConnection;
import Model.NhanVien;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLyNhanVien extends javax.swing.JPanel {

    ThemNV themNV;
    SuaNV suaNV;

    /**
     * Creates new form QuanLyNV
     */
    public QuanLyNhanVien() {
        initComponents();
        loadNhanVien();
    }

    public static void loadNhanVien() {

        String[] array = {"Mã Nhân Viên", "Tên Nhân Viên", "Tài Khoản", "Mật Khẩu", "Chức Vụ", "Địa Chỉ", "CMND", "Số Điện Thoại"};
        DefaultTableModel defaultTableModel = new DefaultTableModel(array, 0);
        DBConnection dBConnection = new DBConnection();
        ArrayList<NhanVien> nhanVienList = dBConnection.getDSNhanVien();
        for (int i = 0; i < nhanVienList.size(); i++) {
            Vector vector = new Vector();
            vector.add(nhanVienList.get(i).getMaNhanVien());
            vector.add(nhanVienList.get(i).getTenNhanVien());
            vector.add(nhanVienList.get(i).getTaiKhoan());
            vector.add(nhanVienList.get(i).getMatKhau());
            vector.add(nhanVienList.get(i).getChucVu().getTenChucVu());
            vector.add(nhanVienList.get(i).getDiaChi());
            vector.add(nhanVienList.get(i).getCmnd());
            vector.add(nhanVienList.get(i).getSdt());
            defaultTableModel.addRow(vector);
        }
        tableQuanLyNhanVien.setRowHeight(35);
        tableQuanLyNhanVien.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuanLyNhanVien = new javax.swing.JTable();
        btnSua = new javax.swing.JLabel();
        btnThem = new javax.swing.JLabel();
        btnXoa = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tableQuanLyNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableQuanLyNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableQuanLyNhanVien);

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setPreferredSize(new java.awt.Dimension(81, 32));
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSuaMousePressed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThemMousePressed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setPreferredSize(new java.awt.Dimension(81, 32));
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnXoaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 528, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMousePressed
        // TODO add your handling code here:
        themNV = new ThemNV(null, true);
        themNV.setVisible(true);
    }//GEN-LAST:event_btnThemMousePressed

    private void btnSuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMousePressed
        // TODO add your handling code here:

        try {
            SuaNV.maNhanVien = tableQuanLyNhanVien.getValueAt(tableQuanLyNhanVien.getSelectedRow(), 0).toString();
            SuaNV.tenNhanVien = tableQuanLyNhanVien.getValueAt(tableQuanLyNhanVien.getSelectedRow(), 1).toString();
            SuaNV.taiKhoan = tableQuanLyNhanVien.getValueAt(tableQuanLyNhanVien.getSelectedRow(), 2).toString();
            SuaNV.matKhau = tableQuanLyNhanVien.getValueAt(tableQuanLyNhanVien.getSelectedRow(), 3).toString();
            SuaNV.diaChi = tableQuanLyNhanVien.getValueAt(tableQuanLyNhanVien.getSelectedRow(), 5).toString();
            SuaNV.cmnd = tableQuanLyNhanVien.getValueAt(tableQuanLyNhanVien.getSelectedRow(), 6).toString();
            SuaNV.sdt = tableQuanLyNhanVien.getValueAt(tableQuanLyNhanVien.getSelectedRow(), 7).toString();
            suaNV = new SuaNV(null, true);
            suaNV.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng bạn muốn chỉnh sửa!!!");
        }
    }//GEN-LAST:event_btnSuaMousePressed

    private void btnXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMousePressed
        // TODO add your handling code here:
        NhanVien nv = new NhanVien();
        nv.setMaNhanVien(tableQuanLyNhanVien.getValueAt(tableQuanLyNhanVien.getSelectedRow(), 0).toString());
        DBConnection dBConnection = new DBConnection();
        int res = JOptionPane.showConfirmDialog(this, "Bạn có muốn tiếp tục?", "Xác nhận ", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            dBConnection.deleteNhanVien(nv);
            loadNhanVien();
        }
    }//GEN-LAST:event_btnXoaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnThem;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tableQuanLyNhanVien;
    // End of variables declaration//GEN-END:variables
}
